version: '3.8'

services:
  db:
    image: postgres:13
    container_name: gameshop-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mtdatabases
      - POSTGRES_DB=GameShop
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - gameshop_services_net

  app:
    build: .
    image: matejtod/gameshop-app
    container_name: gameshop-app
    ports:
      - "9090:9090"
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/GameShop?currentSchema=gameshop
      - spring.datasource.password=mtdatabases
      - spring.jpa.hibernate.ddl-auto=update
    depends_on:
      - db
    networks:
      - gameshop_services_net

volumes:
  db-data:
networks:
  gameshop_services_net:
    driver: bridge
